name = "qr-tracker"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Cloudflare D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "qr-tracker-db"
database_id = "4cf215e0-af7b-44d5-a204-a12b53058473"

# Configurações de CORS para o frontend
[vars]
ALLOWED_ORIGINS = "https://acssjr.github.io,http://localhost:5500,http://127.0.0.1:5500"
